### ISSUE TITLE
Compress multivariate model predictions within proper bounds

### ISSUE THREAD

**Issue by edwardleardi** [IBM/MAX-Weather-Forecaster#19]
Currently the multivariate model which forecasts all 12 weather features does not post process the predictions to ensure they are within allowable bounds. For example, HOURLYVISIBILITY predictions should be within 0-10 miles, but some predictions are slightly above 10 or slightly negative. Similar issues arise for the following variables:

- HOURLYVISIBILITY
- HOURLYRelativeHumidity
- HOURLYWindSpeed
- HOURLYWindDirection
- HOURLYPrecip

**Comment by bdwyer2** [comment]
I added some basic post processing a few weeks ago but there is room for improvement

https://github.com/IBM/MAX-Weather-Forecaster/pull/17/files
