### ISSUE TITLE
Illegal Instruction (core dumped)

### ISSUE THREAD

**Issue by TechEdd** [IBM/MAX-Weather-Forecaster#31]
I made everything I think I need to do, but when doing
`sudo docker run -it -p 5000:5000 max-weather-forecaster`
I get
`Illegal instruction (core dumped)`

![image](https://user-images.githubusercontent.com/30571076/93728120-872ba880-fb8c-11ea-9b11-0ec37635a7e8.png)

Other techniques don't work neither.
Thanks for the help

**Comment by bdwyer2** [comment]
Hi @TechEdd, what kind of CPU are you using? 

Can you please share the output of `cat /proc/cpuinfo`?

**Comment by TechEdd** [comment]
Hi @bdwyer2 ,
Thanks for the answer, I have an i7 920 CPU on a Virtual Machine. Which means I have one core which is use for Ubuntu.
![image](https://user-images.githubusercontent.com/30571076/93820647-78480300-fc2b-11ea-8667-52adef593fb4.png)

**Comment by xuhdev** [comment]
Your processor doesn't seem to support AVX. Looks like this is related to a tensorflow issue: https://github.com/tensorflow/tensorflow/issues/19584

You might wanna try to replace the tensorflow line in `requirements.txt` with a community build or a build by yourself.
